'use client';

import { useState } from 'react';
import { toast } from 'sonner';
import { Code2, Copy, Download } from 'lucide-react';
import { download, slug } from '@/workbench/export/download';

/**
 * A generated diagram with the two escape hatches teams actually ask for:
 * the SVG (drop into a slide or a doc) and the Mermaid source (paste into
 * Confluence, Notion, or a pull request and keep editing it there).
 */
export function DiagramCard({
  title,
  purpose,
  svg,
  mermaid,
  evalName,
  id,
}: {
  title: string;
  purpose: string;
  svg: string;
  mermaid: string;
  evalName: string;
  id: string;
}) {
  const [showSource, setShowSource] = useState(false);

  return (
    <section className="rounded-lg border border-border bg-card">
      <header className="flex flex-wrap items-start gap-3 border-b border-border p-4">
        <div className="min-w-0 flex-1">
          <h2 className="font-semibold">{title}</h2>
          <p className="mt-0.5 text-sm text-muted-foreground">{purpose}</p>
        </div>
        <div className="flex shrink-0 gap-1.5">
          <Action
            icon={<Code2 className="h-3.5 w-3.5" />}
            label={showSource ? 'Hide source' : 'Mermaid'}
            onClick={() => setShowSource((v) => !v)}
          />
          <Action
            icon={<Copy className="h-3.5 w-3.5" />}
            label="Copy"
            onClick={() => {
              navigator.clipboard.writeText(showSource ? mermaid : svg);
              toast.success(showSource ? 'Mermaid source copied' : 'SVG copied');
            }}
          />
          <Action
            icon={<Download className="h-3.5 w-3.5" />}
            label=".svg"
            onClick={() => {
              download(`${slug(evalName)}-${id}.svg`, 'image/svg+xml', svg);
              toast.success('Diagram downloaded');
            }}
          />
        </div>
      </header>

      {showSource ? (
        <pre className="overflow-auto p-4 font-mono text-xs leading-relaxed">{mermaid}</pre>
      ) : (
        <div
          className="overflow-x-auto bg-white p-4"
          // Generated by our own builders from evaluation data; every
          // interpolated value goes through the escaper in workbench/diagrams/svg.
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      )}
    </section>
  );
}

function Action({
  icon,
  label,
  onClick,
}: {
  icon: React.ReactNode;
  label: string;
  onClick: () => void;
}) {
  return (
    <button
      onClick={onClick}
      className="inline-flex items-center gap-1.5 rounded-md border border-border px-2.5 py-1 text-xs font-medium hover:bg-muted"
    >
      {icon} {label}
    </button>
  );
}
