import Link from 'next/link';
import { ArrowRight } from 'lucide-react';
import { Reveal } from '@/components/motion/Reveal';
import { DEMO } from '@/lib/demo-review';

/**
 * The output, shown rather than described.
 *
 * Everything on this page is generated at build time by the same engine the
 * product runs — the real scorer, the real scope rules, the real diagram
 * builders. A visitor asking "what do I actually get" was previously answered
 * with adjectives. This answers it with the artifact.
 */

const decisionTone = (d: string) =>
  d.includes('Remediation') || d === 'Blocked'
    ? 'text-danger'
    : d.includes('Conditions')
      ? 'text-[oklch(0.55_0.13_75)]'
      : 'text-electric';

export function WhatYouGet() {
  const flow = DEMO.diagrams.find((d) => d.id === 'data-flow')!;
  const euAiAct = DEMO.frameworks.find((f) => f.framework.id === 'eu-ai-act');

  return (
    <section className="border-y border-border bg-paper">
      <div className="mx-auto max-w-6xl px-5 py-24 sm:px-8 sm:py-32">
        <Reveal>
          <span className="text-[12px] font-semibold uppercase tracking-[0.16em] text-electric">
            What you get
          </span>
          <h2 className="display-lg mt-4 max-w-3xl">
            This is a real review, made by the real product.
          </h2>
          <p className="mt-5 max-w-2xl text-lg text-muted-foreground">
            Northwind Holdings is piloting Microsoft&nbsp;365 Copilot with 240 staff. Everything
            below was generated by the same engine you&rsquo;d be using — the scores, the scope, the
            diagram, the regulatory mapping. Nothing here is a mockup.
          </p>
        </Reveal>

        {/* The headline call */}
        <Reveal>
          <div className="mt-12 overflow-hidden rounded-2xl border border-border bg-card">
            <div className="flex flex-wrap items-center gap-x-8 gap-y-4 border-b border-border p-7">
              <div>
                <div className="text-[11px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">
                  The call
                </div>
                <div className="mt-1 text-3xl font-semibold tracking-tight text-danger">
                  {DEMO.score.recommendation}
                </div>
              </div>
              <div className="h-10 w-px bg-border max-sm:hidden" />
              <Stat label="Readiness" value={`${DEMO.score.readiness}/100`} />
              <Stat label="Risk" value={DEMO.score.risk} />
              <Stat label="Reviews that apply" value={`${DEMO.lensesRequired} of ${DEMO.lensesTotal}`} />
              <Stat
                label="Signed off"
                value={`${DEMO.score.teamsSignedOff} of ${DEMO.score.requiredTeams}`}
              />
              <Stat label="Evidence complete" value={`${DEMO.score.evidenceCompleteness}%`} />
            </div>

            <div className="grid gap-px bg-border lg:grid-cols-[1.15fr_1fr]">
              {/* Why it's blocked — the thing a reviewer needs first */}
              <div className="bg-card p-7">
                <h3 className="text-[11px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">
                  What&rsquo;s stopping it
                </h3>
                {DEMO.blockers.map((b) => (
                  <div key={b.team} className="mt-3">
                    <div className="font-semibold">{b.team}</div>
                    <ul className="mt-1 space-y-1">
                      {b.items.map((i) => (
                        <li key={i} className="text-[15px] text-danger">
                          {i}
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
                <p className="mt-4 border-l-2 border-border pl-4 text-[15px] leading-relaxed text-muted-foreground">
                  Copilot inherits your existing Microsoft&nbsp;365 permissions. Files over-shared
                  today become searchable by everyone tomorrow — so a permissions review has to land
                  before the pilot widens.
                </p>
                <p className="mt-4 text-sm text-muted-foreground">
                  One critical blocker forces readiness to zero, whatever else is green. That is the
                  point of a blocker.
                </p>
              </div>

              {/* Per-team table */}
              <div className="bg-card p-7">
                <h3 className="text-[11px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">
                  Where each team landed
                </h3>
                <div className="mt-3 space-y-2">
                  {DEMO.teams.slice(0, 8).map((t) => (
                    <div key={t.title} className="flex items-center gap-3 text-sm">
                      <span className="w-40 shrink-0 truncate text-muted-foreground">{t.title}</span>
                      <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-muted">
                        <div
                          className="h-full rounded-full bg-electric"
                          style={{ width: `${t.readiness}%` }}
                        />
                      </div>
                      <span className={`w-10 shrink-0 text-right font-mono text-xs ${decisionTone(t.decision)}`}>
                        {t.readiness}%
                      </span>
                    </div>
                  ))}
                </div>
                <p className="mt-4 text-sm text-muted-foreground">
                  {DEMO.lensesTotal - DEMO.lensesRequired} reviews were skipped as out of scope,
                  including {DEMO.lensesSkipped.slice(0, 2).join(' and ')}. Being told what you can
                  skip is half the value.
                </p>
              </div>
            </div>
          </div>
        </Reveal>

        {/* The diagram — generated, not drawn */}
        <Reveal>
          <div className="mt-6 overflow-hidden rounded-2xl border border-border bg-card">
            <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1 border-b border-border p-7">
              <h3 className="text-xl font-semibold tracking-tight">{flow.title}</h3>
              <p className="text-[15px] text-muted-foreground">{flow.purpose}</p>
            </div>
            <div
              className="overflow-x-auto bg-white p-6"
              // Built by workbench/diagrams from the evaluation above; every
              // interpolated value goes through that module's escaper.
              dangerouslySetInnerHTML={{ __html: flow.svg }}
            />
            <p className="border-t border-border px-7 py-4 text-sm text-muted-foreground">
              Drawn from the answers, not by hand — so it can&rsquo;t drift from the assessment the
              way a slide does. Three more come with it: trust boundary, approval path, and a
              readiness heatmap.
            </p>
          </div>
        </Reveal>

        {/* Regulatory mapping */}
        {euAiAct && (
          <Reveal>
            <div className="mt-6 overflow-hidden rounded-2xl border border-border bg-card">
              <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1 border-b border-border p-7">
                <h3 className="text-xl font-semibold tracking-tight">
                  Mapped to the regulation
                </h3>
                <p className="text-[15px] text-muted-foreground">
                  {euAiAct.framework.authority} — obligations apply from August 2026
                </p>
              </div>
              <div className="grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-3">
                {euAiAct.clauses.slice(0, 6).map((c) => (
                  <div key={c.clause.id} className="bg-card p-5">
                    <div className="flex items-baseline gap-2">
                      <span className="font-mono text-xs font-semibold text-electric">
                        {c.clause.ref}
                      </span>
                      <span className="text-sm font-semibold">{c.clause.title}</span>
                    </div>
                    <p className="mt-1.5 text-sm text-muted-foreground">
                      {c.status === 'out-of-scope'
                        ? 'Out of scope for this tool'
                        : `${Math.round(c.completeness * 100)}% evidenced`}
                    </p>
                  </div>
                ))}
              </div>
              <p className="border-t border-border px-7 py-4 text-sm text-muted-foreground">
                So when an auditor asks where you addressed Article 10, the answer is a control
                somebody signed — not a search through old documents.
              </p>
            </div>
          </Reveal>
        )}

        <Reveal>
          <div className="mt-10 flex flex-wrap items-center gap-x-6 gap-y-3">
            <Link
              href="/signup"
              className="inline-flex h-12 items-center gap-2 rounded-full bg-ink px-7 text-[15px] font-medium text-paper transition-transform hover:scale-[1.02]"
            >
              Do this for your first tool, free <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              href="/example-review"
              className="group inline-flex items-center gap-1.5 text-[15px] font-medium text-foreground"
            >
              Read the whole review document
              <span className="text-electric transition-transform group-hover:translate-x-0.5">
                →
              </span>
            </Link>
          </div>
          <p className="mt-3 text-[15px] text-muted-foreground">
            One tool, three seats, the whole pack. No card.
          </p>
        </Reveal>
      </div>
    </section>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-[11px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">
        {label}
      </div>
      <div className="mt-1 text-xl font-semibold tracking-tight">{value}</div>
    </div>
  );
}
